# Generated by Django 5.0.7 on 2024-08-23 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commande', '0001_initial'),
        ('direction', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id_categ', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MethodePaiement',
            fields=[
                ('id_paiement', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Approvisionnement',
            fields=[
                ('id_appro', models.AutoField(primary_key=True, serialize=False)),
                ('date_achat', models.DateTimeField(auto_now_add=True)),
                ('qte', models.IntegerField()),
                ('prix_achat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('four', models.CharField(default='Inconnu', max_length=255)),
                ('gerant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='direction.gerant')),
                ('site', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='direction.site')),
            ],
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id_paiement', models.AutoField(primary_key=True, serialize=False)),
                ('date_paiement', models.DateTimeField(null=True)),
                ('destinataire', models.IntegerField(choices=[(1, 'Client'), (2, 'Fournisseur')], default=1)),
                ('est_terminee', models.BooleanField(default=False)),
                ('parti_payee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('approvisionnement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion.approvisionnement')),
                ('commande', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='commande.commandetotale')),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id_prod', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='prodcuts_images/')),
                ('image_url', models.URLField()),
                ('nom', models.CharField(max_length=255)),
                ('prix_vente', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prix_achat', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('code_bar', models.CharField(max_length=15, null=True, unique=True)),
                ('stock_urgence', models.IntegerField(default=0)),
                ('categ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.categorie')),
            ],
        ),
        migrations.AddField(
            model_name='approvisionnement',
            name='prod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.produit'),
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id_stock', models.AutoField(primary_key=True, serialize=False)),
                ('qte', models.IntegerField()),
                ('prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.produit')),
                ('site', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='direction.site')),
            ],
        ),
        migrations.CreateModel(
            name='VerificationStock',
            fields=[
                ('id_verif', models.AutoField(primary_key=True, serialize=False)),
                ('date_verif', models.DateTimeField(auto_now_add=True)),
                ('erreur', models.BooleanField(default=False)),
                ('gerant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='direction.gerant')),
            ],
        ),
    ]
