# Generated by Django 5.0.7 on 2024-08-23 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commande', '0001_initial'),
        ('direction', '0001_initial'),
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandeproduit',
            name='prod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.produit'),
        ),
        migrations.AddField(
            model_name='commandetotale',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='direction.client'),
        ),
        migrations.AddField(
            model_name='commandetotale',
            name='gerant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='direction.gerant'),
        ),
        migrations.AddField(
            model_name='commandetotale',
            name='methode_paiement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion.methodepaiement'),
        ),
        migrations.AddField(
            model_name='commandeproduit',
            name='commande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commande.commandetotale'),
        ),
    ]
