BAD_REQUEST = "Mauvaise requête"
INVALID_JSON = "JSON invalide"
INVALID_IDS = "Identifiants invalides"
CONNECTION_SUCCESS = "Connexion réussie"
FIELDS_REQUIRED = "Champs requis non renseignés"
PRODUCT_NOT_FOUND = "Produit non trouvé"
PRODUCT_UPDATED = "Produit mis à jour"
CATEGORY_NOT_FOUND = "Catégorie non trouvée"
MANAGER_NOT_FOUND = "Gérant non trouvé"
TOO_MANY_ATTEMPTS = "Trop de tentatives, Veuillez patienter 1 heure"
CHOOSE_SITE = 'Veuillez choisir un site'
INVALID_CODE_BAR = 'Veuillez saisir un code barre correct'
SUPER_ADMIN_CANT_SELL = 'Un super admin ne peut pas vendre'
QUANTITY_NOT_ENOUGH = 'Quantité supérieur à celle possédé'
QUANTITY_UNDER_WARNING = "Attention, certains produits sont en dessous du seuil d'urgence"
COMMAND_SAVED = 'Commande enregistrée'
COMMAND_NOT_CHANGED = 'Aucun produit à modifier'
COMMAND_CHANGED = "Commande modifiée"
PRODUCT_ADDED = 'Produit ajouté'
PRODUCT_DELETED = 'Product supprimé'
CATEGORY_ADDED = 'Catégorie ajoutée'
CATEGORY_DELETED = 'Catégorie supprimée'
MANAGER_ADDED = 'Gérant ajouté'
SUPER_ADMIN_CANT_BE_DELETED = 'Un super admin ne peut pas être supprimé'
MANAGER_DELETED = 'Gérant supprimé'
MANAGER_PROMOTED = 'Gérant promu'
MANAGER_DEMOTED = 'Gérant rétrogradé'
SITE_ALREADY_EXISTS = 'Site déjà existant'
SITE_ADDED = 'Site ajouté'
VERIFICATION_ADDED = 'Vérification ajoutée'
CANT_PAY_MORE = 'La somme payée ne peut pas être supérieure à la somme totale'
PAYMENT_UPDATED = 'Paiement mis à jour'
BAD_SEARCH = "Mauvaise Recherche"
COMMAND_CANT_BE_DOWNLOADED = "Vous n'avez pas le droit de télécharger cette commande"
UNKNOWN_CATEGORY = 'Catégorie introuvable'
UNKNOWN_PRODUCT = 'Produit introuvable'
UNKNOWN_COMMAND = 'Commande introuvable'
