# Generated by Django 5.0.7 on 2024-08-23 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id_cli', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Parametre',
            fields=[
                ('nom', models.IntegerField(choices=[(1, 'bot_token'), (2, 'chat_id'), (3, 'currency'), (4, 'phone_number')], primary_key=True, serialize=False)),
                ('valeur', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('nom', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Gerant',
            fields=[
                ('gerant', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('mdp', models.CharField(max_length=255)),
                ('est_admin', models.BooleanField(default=False)),
                ('est_super_admin', models.BooleanField(default=False)),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='direction.site')),
            ],
        ),
    ]
